"""add count colum to assosiate table

Revision ID: 35d3295b7425
Revises: 3ab9408e0299
Create Date: 2025-08-02 13:50:21.167898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35d3295b7425"
down_revision: Union[str, Sequence[str], None] = "3ab9408e0299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association_table",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_association_table", "count")
    # ### end Alembic commands ###
