"""add unit colum to assosiate table

Revision ID: 56b0646e3e86
Revises: 35d3295b7425
Create Date: 2025-08-02 15:37:40.492448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56b0646e3e86"
down_revision: Union[str, Sequence[str], None] = "35d3295b7425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association_table",
        sa.Column("unit_price", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_association_table", "unit_price")
    # ### end Alembic commands ###
